import React, { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";
import {
  ArrowRight, CheckCircle, TrendingUp, Target, Mail,
  BarChart2, Zap, Search, Users, Brain, ChevronRight,
  Sun, Moon, Menu, X, Sparkles, Clock, DollarSign,
  AlertTriangle, ShieldCheck, Globe, RefreshCw, Star,
} from "lucide-react";
import { BRAND } from "../brand";

// ─── Data ───────────────────────────────────────────────────────────────────

const RESEARCH_STATS = [
  {
    stat: "61%",
    label: "of marketers say generating quality leads is their #1 challenge",
    source: "HubSpot State of Marketing Report, 2023",
    color: "text-red-400",
    bg: "bg-red-500/10",
    border: "border-red-500/20",
  },
  {
    stat: "66%",
    label: "of a salesperson's day is spent on non-selling tasks — research, admin, manual outreach",
    source: "Salesforce State of Sales, 2023",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
  },
  {
    stat: "60%+",
    label: "rise in customer acquisition costs over the past five years",
    source: "Harvard Business Review, 2022",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/20",
  },
  {
    stat: "50%",
    label: "more sales-ready leads generated by companies that invest in lead nurturing — at 33% lower cost",
    source: "Forrester Research",
    color: "text-violet-400",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
  },
];

const PROBLEM_CARDS = [
  {
    icon: <Search size={22} />,
    title: "Finding the right leads is guesswork",
    body: "Most teams buy generic contact lists or rely on cold outreach to untargeted audiences. McKinsey estimates that poor targeting wastes up to 37 cents of every marketing dollar spent.",
    tag: "Discovery",
  },
  {
    icon: <Clock size={22} />,
    title: "Outreach is manual and doesn't scale",
    body: "Sales reps spend 21 hours a week on research, personalisation, and follow-up. That's time not spent closing. Gartner projects 75% of B2B sales orgs will adopt AI-guided selling by 2025 — most are still far behind.",
    tag: "Outreach",
  },
  {
    icon: <DollarSign size={22} />,
    title: "Acquisition costs keep climbing",
    body: "Customer acquisition costs have risen over 60% in five years (HBR, 2022). Without intent-based targeting and automation, growing companies pay more per lead with diminishing returns.",
    tag: "Cost",
  },
  {
    icon: <AlertTriangle size={22} />,
    title: "One-size emails kill conversion",
    body: "Generic blasts see open rates below 20% and reply rates under 2%. PwC found that 73% of buyers say personalised experience is a key purchase driver — yet 80% of outreach is still mass-templated.",
    tag: "Conversion",
  },
];

const FEATURES = [
  {
    icon: <Globe size={22} />,
    title: "AI Website Analysis",
    body: "Connecttr reads your client's website and extracts their services, ICP, and search intents automatically. No forms, no manual briefing.",
  },
  {
    icon: <Search size={22} />,
    title: "Intent-Based Lead Discovery",
    body: "Platform-specific queries target leads who are already signalling intent — posting about needing your service, hiring, or recommending on LinkedIn, Reddit, and beyond.",
  },
  {
    icon: <Users size={22} />,
    title: "Contact Enrichment",
    body: "Hunter.io integration, multi-format email synthesis, and MX validation ensure you reach real inboxes — not just names on a list.",
  },
  {
    icon: <Brain size={22} />,
    title: "AI-Crafted Outreach",
    body: "Gemini 2.5 Flash writes three personalised email variants per lead, matched to their role, company context, and the outreach tone you choose.",
  },
  {
    icon: <Mail size={22} />,
    title: "Unified Email Hub",
    body: "A full conversation view: send, receive, and track replies across all campaigns from a single threaded inbox with open and click tracking.",
  },
  {
    icon: <BarChart2 size={22} />,
    title: "Analytics Intelligence",
    body: "A/B template testing with Thompson Sampling, intent scoring, reply classification, and a campaign analytics dashboard that shows what's actually working.",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Describe your campaign",
    body: "Enter your client's website URL or a plain-text brief. Connecttr extracts their services, ideal customers, and builds targeted search queries automatically.",
    tag: "Analysis",
  },
  {
    step: "02",
    title: "Discover intent-matched leads",
    body: "AI searches across platforms for people actively signalling they need what your client offers. Results show real names, roles, companies, and verified contact info.",
    tag: "Discovery",
  },
  {
    step: "03",
    title: "Review, then launch",
    body: "A review modal shows every lead grouped by email status. Pick who to include, approve, and Connecttr generates personalised email drafts for each. You send in one click.",
    tag: "Outreach",
  },
];

const IMPACT_STATS = [
  { value: "3×", label: "more leads discovered vs manual Google search" },
  { value: "66%", label: "of sales time reclaimed from manual prospecting" },
  { value: "50%", label: "lower cost-per-lead vs traditional list purchasing" },
  { value: "47%", label: "larger deal sizes from nurtured vs cold leads (Demand Gen Report)" },
];

const NAV_LINKS = ["Features", "How It Works", "Research", "Pricing"];

// ─── Sub-components ──────────────────────────────────────────────────────────

const Badge = ({ children, className = "" }) => (
  <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold border ${className}`}>
    {children}
  </span>
);

const SectionLabel = ({ children }) => (
  <Badge className="bg-royal-amethyst/10 border-royal-amethyst/30 text-royal-amethyst mb-4">
    <Sparkles size={11} />
    {children}
  </Badge>
);

const ResearchCard = ({ stat, label, source, color, bg, border }) => (
  <div className={`rounded-2xl border p-6 ${bg} ${border} flex flex-col gap-3 theme-surface`}>
    <div className={`text-4xl font-extrabold tracking-tight ${color}`}>{stat}</div>
    <p className="text-mist text-sm leading-relaxed font-medium">{label}</p>
    <p className={`text-xs font-medium opacity-60 ${color} mt-auto`}>{source}</p>
  </div>
);

const ProblemCard = ({ icon, title, body, tag }) => (
  <div className="group rounded-2xl border border-overlay/10 bg-slate/60 p-6 hover:border-royal-amethyst/30 hover:bg-midnight-plum/60 transition-all duration-300 theme-surface">
    <div className="flex items-start justify-between mb-4">
      <div className="p-2.5 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400">
        {icon}
      </div>
      <span className="text-[10px] font-bold uppercase tracking-widest text-soft-violet/60 border border-overlay/10 px-2 py-1 rounded-full">
        {tag}
      </span>
    </div>
    <h3 className="font-bold text-mist text-base mb-2 group-hover:text-royal-amethyst transition-colors">{title}</h3>
    <p className="text-soft-violet text-sm leading-relaxed">{body}</p>
  </div>
);

const FeatureCard = ({ icon, title, body }) => (
  <div className="group rounded-2xl border border-overlay/10 bg-slate/40 p-6 hover:border-royal-amethyst/40 hover:bg-midnight-plum/40 hover:-translate-y-0.5 transition-all duration-200 theme-surface">
    <div className="p-2.5 rounded-xl bg-royal-amethyst/15 border border-royal-amethyst/20 text-royal-amethyst w-fit mb-4 group-hover:bg-royal-amethyst/25 transition-colors">
      {icon}
    </div>
    <h3 className="font-bold text-mist text-base mb-2">{title}</h3>
    <p className="text-soft-violet text-sm leading-relaxed">{body}</p>
  </div>
);

const StepCard = ({ step, title, body, tag, isLast }) => (
  <div className="flex gap-5 relative">
    <div className="flex flex-col items-center">
      <div className="w-12 h-12 rounded-2xl bg-royal-amethyst flex items-center justify-center text-white font-extrabold text-sm shadow-glow-sm flex-shrink-0">
        {step}
      </div>
      {!isLast && <div className="w-px flex-1 mt-3 bg-gradient-to-b from-royal-amethyst/40 to-transparent min-h-[2rem]" />}
    </div>
    <div className="pb-10">
      <span className="text-[10px] font-bold uppercase tracking-widest text-royal-amethyst mb-2 block">{tag}</span>
      <h3 className="font-bold text-mist text-lg mb-2">{title}</h3>
      <p className="text-soft-violet text-sm leading-relaxed max-w-md">{body}</p>
    </div>
  </div>
);

// ─── Main Component ──────────────────────────────────────────────────────────

const LandingPage = () => {
  const { user } = useAuth();
  const { theme, toggle } = useTheme();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const heroRef = useRef(null);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const handleCTA = () => navigate(user ? "/dashboard" : "/login");

  const scrollTo = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setMenuOpen(false);
  };

  return (
    <div className="min-h-screen bg-ink text-mist font-sans overflow-x-hidden">

      {/* ── Background blobs ── */}
      <div className="fixed top-[-20%] left-[-15%] w-[60%] h-[60%] bg-royal-amethyst rounded-full blur-[160px] opacity-[0.12] pointer-events-none z-0" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[45%] h-[55%] bg-midnight-plum rounded-full blur-[140px] opacity-[0.18] pointer-events-none z-0" />
      <div className="fixed top-[40%] right-[20%] w-[25%] h-[30%] bg-royal-amethyst rounded-full blur-[120px] opacity-[0.06] pointer-events-none z-0" />

      {/* ── Navbar ── */}
      <header className={`fixed top-0 inset-x-0 z-50 transition-all duration-300 ${scrolled ? "bg-ink/90 backdrop-blur-xl border-b border-overlay/10 shadow-xl" : ""}`}>
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          {/* Logo */}
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>
            <div className="w-8 h-8 rounded-xl bg-royal-amethyst/20 border border-royal-amethyst/30 flex items-center justify-center shadow-glow-sm">
              <img src="/clogo.png" alt={BRAND} className="w-5 h-5 object-contain" onError={e => e.target.style.display = "none"} />
            </div>
            <span className="font-extrabold text-lg tracking-tight text-mist">{BRAND}</span>
          </div>

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-1">
            {[["Features", "features"], ["How It Works", "how-it-works"], ["Research", "research"], ["Pricing", "pricing"]].map(([label, id]) => (
              <button key={id} onClick={() => scrollTo(id)}
                className="px-4 py-2 rounded-lg text-sm font-medium text-soft-violet hover:text-mist hover:bg-overlay/8 transition-all duration-200">
                {label}
              </button>
            ))}
          </nav>

          {/* Right actions */}
          <div className="flex items-center gap-2">
            <button onClick={toggle} className="hidden md:flex p-2 rounded-lg text-soft-violet hover:text-mist hover:bg-overlay/8 transition-all">
              {theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}
            </button>
            <button onClick={handleCTA}
              className="hidden md:flex items-center gap-2 bg-royal-amethyst text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-royal-amethyst/90 shadow-glow-sm hover:shadow-glow transition-all duration-200 active:scale-[0.97]">
              {user ? "Go to Dashboard" : "Get Started"}
              <ArrowRight size={15} />
            </button>
            <button className="md:hidden p-2 text-soft-violet hover:text-mist" onClick={() => setMenuOpen(o => !o)}>
              {menuOpen ? <X size={22} /> : <Menu size={22} />}
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="md:hidden bg-ink/95 backdrop-blur-xl border-t border-overlay/10 px-6 py-4 space-y-1">
            {[["Features", "features"], ["How It Works", "how-it-works"], ["Research", "research"], ["Pricing", "pricing"]].map(([label, id]) => (
              <button key={id} onClick={() => scrollTo(id)}
                className="w-full text-left px-4 py-3 rounded-xl text-sm font-medium text-soft-violet hover:text-mist hover:bg-overlay/8 transition-all">
                {label}
              </button>
            ))}
            <button onClick={handleCTA}
              className="w-full mt-2 flex items-center justify-center gap-2 bg-royal-amethyst text-white px-4 py-3 rounded-xl text-sm font-semibold">
              {user ? "Go to Dashboard" : "Get Started"} <ArrowRight size={15} />
            </button>
          </div>
        )}
      </header>

      {/* ── Hero ── */}
      <section ref={heroRef} className="relative pt-32 pb-24 px-6 text-center max-w-5xl mx-auto">
        <Badge className="bg-royal-amethyst/10 border-royal-amethyst/30 text-royal-amethyst mb-6">
          <Sparkles size={11} /> AI-Powered B2B Lead Generation
        </Badge>

        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight leading-[1.08] mb-6">
          From{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-royal-amethyst via-lilac-mist to-soft-violet">
            Intent
          </span>
          {" "}to{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-soft-violet via-lilac-mist to-royal-amethyst">
            Inbox
          </span>
          .
        </h1>

        <p className="text-xl md:text-2xl text-soft-violet max-w-3xl mx-auto leading-relaxed mb-10">
          Connecttr finds the people who already need your services, enriches their contact info, and sends AI-crafted outreach — so your team closes instead of prospecting.
        </p>

        <div className="flex flex-col sm:flex-row gap-3 justify-center mb-16">
          <button onClick={handleCTA}
            className="flex items-center justify-center gap-2 bg-royal-amethyst text-white px-8 py-4 rounded-xl text-base font-bold hover:bg-royal-amethyst/90 shadow-glow hover:shadow-glow-lg transition-all duration-200 active:scale-[0.98]">
            {user ? "Open Dashboard" : "Start for Free"}
            <ArrowRight size={18} />
          </button>
          <button onClick={() => scrollTo("how-it-works")}
            className="flex items-center justify-center gap-2 border border-overlay/20 text-mist px-8 py-4 rounded-xl text-base font-semibold hover:bg-overlay/8 hover:border-royal-amethyst/40 transition-all duration-200">
            See How It Works
            <ChevronRight size={18} />
          </button>
        </div>

        {/* Mini trust line */}
        <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-soft-violet/60">
          {["No credit card required", "Invite-only access", "Deployed on enterprise infrastructure"].map(t => (
            <span key={t} className="flex items-center gap-1.5">
              <CheckCircle size={13} className="text-emerald-400" /> {t}
            </span>
          ))}
        </div>
      </section>

      {/* ── Research Stats ── */}
      <section id="research" className="relative px-6 py-20 max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <SectionLabel>Backed by Research</SectionLabel>
          <h2 className="text-3xl md:text-4xl font-extrabold text-mist tracking-tight mb-4">
            Lead generation is broken.<br className="hidden md:block" /> The data is unambiguous.
          </h2>
          <p className="text-soft-violet max-w-2xl mx-auto">
            McKinsey, Forrester, HubSpot, Harvard Business Review — every major research body has documented the same crisis. Businesses burn budget on leads that don't convert, outreach that doesn't land, and teams that spend more time prospecting than selling.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-10">
          {RESEARCH_STATS.map((s) => <ResearchCard key={s.stat} {...s} />)}
        </div>

        {/* Pull quote */}
        <blockquote className="rounded-2xl border border-royal-amethyst/20 bg-royal-amethyst/5 p-8 text-center theme-surface">
          <p className="text-xl md:text-2xl font-semibold text-mist leading-relaxed max-w-4xl mx-auto italic">
            "Personalisation can reduce customer acquisition costs by up to{" "}
            <span className="text-royal-amethyst not-italic font-extrabold">50%</span>{" "}
            while simultaneously lifting revenue by{" "}
            <span className="text-royal-amethyst not-italic font-extrabold">5–15%</span>."
          </p>
          <p className="mt-4 text-soft-violet text-sm font-medium">— McKinsey & Company, Next in Personalization 2021</p>
        </blockquote>
      </section>

      {/* ── Problem ── */}
      <section className="relative px-6 py-20 max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <SectionLabel>The Problem</SectionLabel>
          <h2 className="text-3xl md:text-4xl font-extrabold text-mist tracking-tight mb-4">
            Four compounding failures<br className="hidden md:block" /> that kill growth
          </h2>
          <p className="text-soft-violet max-w-2xl mx-auto">
            Most B2B companies aren't struggling with effort — they're struggling with inefficiency baked into their acquisition process from day one.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {PROBLEM_CARDS.map((c) => <ProblemCard key={c.title} {...c} />)}
        </div>
      </section>

      {/* ── Solution bridge ── */}
      <section className="relative px-6 py-20">
        <div className="max-w-7xl mx-auto rounded-3xl border border-royal-amethyst/25 bg-gradient-to-br from-royal-amethyst/10 via-midnight-plum/60 to-ink/80 p-10 md:p-16 overflow-hidden">
          {/* Decorative orb */}
          <div className="absolute -top-20 -right-20 w-64 h-64 bg-royal-amethyst rounded-full blur-[80px] opacity-20 pointer-events-none" />

          <div className="relative max-w-3xl">
            <SectionLabel>The Solution</SectionLabel>
            <h2 className="text-3xl md:text-5xl font-extrabold text-mist tracking-tight mb-6 leading-[1.1]">
              Connecttr turns your campaign brief into a full pipeline — automatically.
            </h2>
            <p className="text-soft-violet text-lg leading-relaxed mb-8">
              Instead of buying lists or guessing who to target, Connecttr reads your client's website, builds intent-based search queries, discovers people actively signalling they need your service, finds their contact info, and writes personalised outreach — all in minutes.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
              {[
                { icon: <Target size={18} />, label: "Intent-based targeting", desc: "Reach people who want what you offer" },
                { icon: <Zap size={18} />, label: "Automated discovery", desc: "From URL to leads in under 3 minutes" },
                { icon: <ShieldCheck size={18} />, label: "Verified contacts", desc: "Real emails, MX-validated domains" },
              ].map(({ icon, label, desc }) => (
                <div key={label} className="flex gap-3 p-4 rounded-xl bg-overlay/5 border border-overlay/10">
                  <span className="text-royal-amethyst mt-0.5 flex-shrink-0">{icon}</span>
                  <div>
                    <p className="font-semibold text-mist text-sm">{label}</p>
                    <p className="text-soft-violet text-xs mt-0.5">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
            <button onClick={handleCTA}
              className="flex items-center gap-2 bg-royal-amethyst text-white px-6 py-3 rounded-xl font-bold hover:bg-royal-amethyst/90 shadow-glow hover:shadow-glow-lg transition-all duration-200 active:scale-[0.97]">
              {user ? "Open your dashboard" : "Get early access"} <ArrowRight size={16} />
            </button>
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section id="features" className="relative px-6 py-20 max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <SectionLabel>Platform Features</SectionLabel>
          <h2 className="text-3xl md:text-4xl font-extrabold text-mist tracking-tight mb-4">
            Everything in one place
          </h2>
          <p className="text-soft-violet max-w-xl mx-auto">
            Connecttr replaces the stack of spreadsheets, email finders, copywriting tools, and CRM plugins your team currently juggles.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURES.map((f) => <FeatureCard key={f.title} {...f} />)}
        </div>
      </section>

      {/* ── How It Works ── */}
      <section id="how-it-works" className="relative px-6 py-20 max-w-7xl mx-auto">
        <div className="grid md:grid-cols-2 gap-16 items-start">
          <div>
            <SectionLabel>How It Works</SectionLabel>
            <h2 className="text-3xl md:text-4xl font-extrabold text-mist tracking-tight mb-4">
              Three steps from brief to booked meeting
            </h2>
            <p className="text-soft-violet leading-relaxed mb-10">
              Connecttr's pipeline is designed around the reality of B2B sales — you need leads fast, with context, and with a personal touch that scales.
            </p>
            <div>
              {HOW_IT_WORKS.map((s, i) => (
                <StepCard key={s.step} {...s} isLast={i === HOW_IT_WORKS.length - 1} />
              ))}
            </div>
          </div>

          {/* Visual panel */}
          <div className="sticky top-24 rounded-3xl border border-overlay/10 bg-midnight-plum/60 overflow-hidden shadow-2xl theme-surface">
            {/* Mock header */}
            <div className="flex items-center gap-2 px-5 py-4 border-b border-overlay/10 bg-overlay/5">
              <div className="w-3 h-3 rounded-full bg-red-400/70" />
              <div className="w-3 h-3 rounded-full bg-yellow-400/70" />
              <div className="w-3 h-3 rounded-full bg-emerald-400/70" />
              <span className="ml-3 text-xs text-soft-violet font-mono">connecttr — campaign discovery</span>
            </div>
            {/* Mock pipeline UI */}
            <div className="p-6 space-y-4">
              <div className="rounded-xl bg-royal-amethyst/10 border border-royal-amethyst/25 p-4">
                <p className="text-[10px] font-bold uppercase tracking-widest text-royal-amethyst mb-2">Campaign Brief</p>
                <div className="h-2 bg-royal-amethyst/30 rounded-full w-3/4 mb-1.5" />
                <div className="h-2 bg-royal-amethyst/20 rounded-full w-1/2" />
              </div>
              {[
                { label: "Search 1/5 — 12 candidates found", pct: 100, color: "bg-emerald-500" },
                { label: "Search 2/5 — 8 candidates found",  pct: 100, color: "bg-emerald-500" },
                { label: "Search 3/5 — Finding contact info…", pct: 60, color: "bg-royal-amethyst" },
              ].map((r, i) => (
                <div key={i} className="rounded-xl bg-overlay/5 border border-overlay/8 p-4">
                  <p className="text-xs text-soft-violet mb-2">{r.label}</p>
                  <div className="h-1.5 rounded-full bg-overlay/10">
                    <div className={`h-full rounded-full ${r.color} transition-all`} style={{ width: `${r.pct}%` }} />
                  </div>
                </div>
              ))}
              <div className="rounded-xl bg-overlay/5 border border-overlay/8 p-4 space-y-2.5">
                {[
                  { name: "Sarah Chen", role: "Founder · StudioMade", status: "Verified", color: "bg-emerald-500/20 text-emerald-400 border-emerald-500/20" },
                  { name: "James Park", role: "CEO · Lumencraft", status: "Verified", color: "bg-emerald-500/20 text-emerald-400 border-emerald-500/20" },
                  { name: "Mia Torres", role: "CMO · Arbor Labs", status: "Guessed", color: "bg-amber-500/20 text-amber-400 border-amber-500/20" },
                ].map(({ name, role, status, color }) => (
                  <div key={name} className="flex items-center justify-between">
                    <div>
                      <p className="text-xs font-semibold text-mist">{name}</p>
                      <p className="text-[10px] text-soft-violet">{role}</p>
                    </div>
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${color}`}>{status}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Impact Numbers ── */}
      <section className="relative px-6 py-20">
        <div className="max-w-7xl mx-auto rounded-3xl border border-overlay/10 bg-slate/40 p-10 md:p-16 theme-surface">
          <div className="text-center mb-12">
            <SectionLabel>Impact</SectionLabel>
            <h2 className="text-3xl md:text-4xl font-extrabold text-mist tracking-tight">
              The numbers that matter
            </h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {IMPACT_STATS.map(({ value, label }) => (
              <div key={label} className="text-center">
                <div className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-royal-amethyst to-lilac-mist mb-3">
                  {value}
                </div>
                <p className="text-soft-violet text-sm leading-snug">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing / CTA ── */}
      <section id="pricing" className="relative px-6 py-20 max-w-4xl mx-auto text-center">
        <SectionLabel>Early Access</SectionLabel>
        <h2 className="text-3xl md:text-5xl font-extrabold text-mist tracking-tight mb-4">
          Built for agencies and<br className="hidden md:block" /> ambitious B2B teams
        </h2>
        <p className="text-soft-violet text-lg max-w-2xl mx-auto mb-12">
          Connecttr is currently invite-only while we validate results with our first cohort of clients. Apply for early access and we'll get you set up personally.
        </p>

        {/* Pricing cards */}
        <div className="grid md:grid-cols-2 gap-6 mb-10 text-left">
          {[
            {
              name: "Starter",
              price: "Free",
              desc: "For solopreneurs and small agencies exploring AI-driven outreach.",
              features: ["3 active campaigns", "100 leads / month", "AI email drafting", "Email Hub with threading", "Basic analytics"],
              cta: "Get Started Free",
              highlight: false,
            },
            {
              name: "Growth",
              price: "$79",
              period: "/ month",
              desc: "For agencies running multiple clients with high-volume prospecting needs.",
              features: ["Unlimited campaigns", "1,000 leads / month", "Hunter.io enrichment", "A/B template testing", "Advanced analytics + export", "Priority support"],
              cta: "Start Free Trial",
              highlight: true,
            },
          ].map(({ name, price, period, desc, features, cta, highlight }) => (
            <div key={name}
              className={`rounded-2xl border p-8 theme-surface ${highlight
                ? "border-royal-amethyst/50 bg-royal-amethyst/10 shadow-glow-sm"
                : "border-overlay/15 bg-slate/40"}`}>
              {highlight && (
                <Badge className="bg-royal-amethyst/20 border-royal-amethyst/40 text-royal-amethyst mb-4">
                  <Star size={10} /> Most Popular
                </Badge>
              )}
              <h3 className="font-extrabold text-xl text-mist mb-1">{name}</h3>
              <div className="flex items-baseline gap-1 mb-3">
                <span className="text-4xl font-extrabold text-mist">{price}</span>
                {period && <span className="text-soft-violet text-sm">{period}</span>}
              </div>
              <p className="text-soft-violet text-sm mb-6">{desc}</p>
              <ul className="space-y-2.5 mb-8">
                {features.map(f => (
                  <li key={f} className="flex items-center gap-2.5 text-sm text-mist">
                    <CheckCircle size={15} className="text-emerald-400 flex-shrink-0" /> {f}
                  </li>
                ))}
              </ul>
              <button onClick={handleCTA}
                className={`w-full py-3 rounded-xl font-bold text-sm transition-all duration-200 active:scale-[0.98] ${highlight
                  ? "bg-royal-amethyst text-white hover:bg-royal-amethyst/90 shadow-glow hover:shadow-glow-lg"
                  : "border border-overlay/20 text-mist hover:bg-overlay/8 hover:border-royal-amethyst/30"}`}>
                {cta}
              </button>
            </div>
          ))}
        </div>

        <p className="text-xs text-soft-violet/60">
          All plans include a 14-day free trial. No credit card required to start.
        </p>
      </section>

      {/* ── Final CTA banner ── */}
      <section className="relative px-6 pb-20 max-w-7xl mx-auto">
        <div className="rounded-3xl border border-royal-amethyst/30 bg-gradient-to-br from-royal-amethyst/15 via-midnight-plum/50 to-transparent p-12 md:p-20 text-center overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-transparent to-ink/40 pointer-events-none rounded-3xl" />
          <div className="relative">
            <h2 className="text-3xl md:text-5xl font-extrabold text-mist mb-4 tracking-tight">
              Stop paying for leads<br className="hidden md:block" /> that don't convert.
            </h2>
            <p className="text-soft-violet text-lg max-w-xl mx-auto mb-8">
              Join the teams using Connecttr to find real buyers, reach them personally, and close faster.
            </p>
            <button onClick={handleCTA}
              className="inline-flex items-center gap-2 bg-royal-amethyst text-white px-10 py-4 rounded-2xl text-lg font-bold hover:bg-royal-amethyst/90 shadow-glow-lg hover:shadow-glow transition-all duration-200 active:scale-[0.97]">
              {user ? "Open Dashboard" : "Request Access"}
              <ArrowRight size={20} />
            </button>
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-overlay/10 px-6 py-12">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
            <div className="col-span-2 md:col-span-1">
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-7 h-7 rounded-lg bg-royal-amethyst/20 border border-royal-amethyst/30 flex items-center justify-center">
                  <img src="/clogo.png" alt={BRAND} className="w-4 h-4 object-contain" onError={e => e.target.style.display = "none"} />
                </div>
                <span className="font-extrabold text-mist">{BRAND}</span>
              </div>
              <p className="text-soft-violet text-sm leading-relaxed">
                AI-powered B2B lead generation and outreach automation.
              </p>
            </div>

            {[
              { heading: "Product", links: ["Features", "How It Works", "Pricing", "Changelog"] },
              { heading: "Research", links: ["HubSpot Report", "McKinsey Study", "Forrester Insights", "Gartner B2B"] },
              { heading: "Company",  links: ["About", "Privacy Policy", "Terms of Service", "Contact"] },
            ].map(({ heading, links }) => (
              <div key={heading}>
                <h4 className="text-xs font-bold uppercase tracking-widest text-soft-violet/60 mb-4">{heading}</h4>
                <ul className="space-y-2.5">
                  {links.map(l => (
                    <li key={l}>
                      <span className="text-soft-violet text-sm hover:text-mist transition-colors cursor-pointer">{l}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="border-t border-overlay/8 pt-6 flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-soft-violet/50 text-xs">© {new Date().getFullYear()} {BRAND}. All rights reserved.</p>
            <div className="flex items-center gap-4">
              <button onClick={toggle}
                className="flex items-center gap-2 text-soft-violet/60 hover:text-mist text-xs transition-colors">
                {theme === "dark" ? <><Sun size={13} /> Light Mode</> : <><Moon size={13} /> Dark Mode</>}
              </button>
              <button onClick={handleCTA}
                className="flex items-center gap-1.5 text-royal-amethyst text-xs font-semibold hover:underline">
                {user ? "Dashboard" : "Sign In"} <ArrowRight size={12} />
              </button>
            </div>
          </div>
        </div>
      </footer>

    </div>
  );
};

export default LandingPage;
