import React, { useState } from 'react';
import { Card } from '../components/ui/card';
import { Mail, Send, Loader2, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const QuickSend = () => {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [formData, setFormData] = useState({
        to_email: '',
        subject: '',
        body: ''
    });

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);

        try {
            // "Default" sender - ideally this comes from user settings or auth
            // For now hardcoded to match system default or user input requirement
            // But SendReq requires from_email. 
            // We'll let user type it or assume a default if we had one.
            // Actually SendReq requires from_email. Let's add that field or hardcode valid one.
            // Let's assume user has a configured sender. for now I'll put a placeholder or let user type it?
            // "Quick Send" usually implies using my default identity.
            // I'll add a "From" field pre-filled if possible, or just require it.
            // Wait, SendReq from UI usually gets from_email from the selected Persona/Campaign.
            // Here we have no campaign.
            // Let's default to a known sender or ask user.

            // Re-reading requirements: Inputs: To, Subject, Body.
            // I'll hardcode from_email for now to "ayush@connecttr.com" or similar valid sender 
            // OR better, ask user.

            // Let's check typical usage.
            // I'll better add a From field to be safe.

            const payload = {
                lead_id: "", // generated by backend
                campaign_id: "default",
                from_email: "ayush@connecttr.com", // TODO: Fetch from user profile
                to_email: formData.to_email,
                choice: "A",
                draft: {
                    subject: formData.subject,
                    body: formData.body
                }
            };

            const res = await fetch('http://localhost:8000/emailhub/send', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const err = await res.json().catch(() => ({ detail: "Send failed" }));
                throw new Error(err.detail || "Send failed");
            }

            const data = await res.json();
            // Redirect to threads/inbox view?
            // "Redirect to EmailHub conversation view on success"
            navigate('/email-hub');

        } catch (error) {
            alert(error.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="p-8 max-w-4xl mx-auto space-y-8 animate-in fade-in duration-500">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="space-y-1">
                    <h1 className="text-3xl font-bold tracking-tight text-white flex items-center gap-3">
                        <div className="p-2 rounded-lg bg-indigo-500/20 text-indigo-400">
                            <Send className="w-6 h-6" />
                        </div>
                        Quick Send
                    </h1>
                    <p className="text-slate-400">
                        Send an ad-hoc tracked email without creating a campaign.
                    </p>
                </div>
            </div>

            <Card className="p-6 bg-slate-900/50 border-slate-800 backdrop-blur-xl">
                <form onSubmit={handleSubmit} className="space-y-6">
                    <div className="grid grid-cols-1 gap-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-300">To Email</label>
                            <input
                                required
                                type="email"
                                className="w-full bg-slate-950/50 border border-slate-800 rounded-lg px-4 py-2.5 text-slate-200 focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all outline-none"
                                placeholder="lead@example.com"
                                value={formData.to_email}
                                onChange={e => setFormData({ ...formData, to_email: e.target.value })}
                            />
                        </div>

                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-300">Subject</label>
                            <input
                                required
                                type="text"
                                className="w-full bg-slate-950/50 border border-slate-800 rounded-lg px-4 py-2.5 text-slate-200 focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all outline-none"
                                placeholder="Hello there..."
                                value={formData.subject}
                                onChange={e => setFormData({ ...formData, subject: e.target.value })}
                            />
                        </div>

                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-300">Message Body</label>
                            <textarea
                                required
                                rows={8}
                                className="w-full bg-slate-950/50 border border-slate-800 rounded-lg px-4 py-2.5 text-slate-200 focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-all outline-none resize-none font-mono text-sm"
                                placeholder="Write your message..."
                                value={formData.body}
                                onChange={e => setFormData({ ...formData, body: e.target.value })}
                            />
                        </div>
                    </div>

                    <div className="flex justify-end gap-3 pt-4 border-t border-slate-800/50">
                        <button
                            type="button"
                            onClick={() => navigate(-1)}
                            className="px-4 py-2 text-slate-400 hover:text-white transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={loading}
                            className="flex items-center gap-2 px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-all shadow-lg shadow-indigo-900/20 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                            Send Email
                        </button>
                    </div>
                </form>
            </Card>
        </div>
    );
};

export default QuickSend;
